# Generated by Django 3.2.9 on 2022-09-14 13:12

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(blank=True, max_length=10, null=True, validators=[app.validators.validate_date])),
                ('educenter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.educenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RevenueGoal',
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=14, validators=[app.validators.validate_date]),
        ),
    ]
