# Generated by Django 3.2.9 on 2022-09-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_revenue_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='educenter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.educenter'),
        ),
    ]
