# Generated by Django 3.2.9 on 2022-09-15 03:01

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_revenue_educenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=15, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='educenter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reveducen', to='app.educenter'),
        ),
    ]
