# Generated by Django 3.2.9 on 2022-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220915_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
