# Generated by Django 3.2.9 on 2022-09-15 16:56

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_revenue_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=15, null=True)),
                ('month', models.PositiveIntegerField(blank=True, default=9, null=True, validators=[app.validators.validate_date])),
                ('year', models.PositiveIntegerField(blank=True, default=2022, null=True, validators=[app.validators.validate_year])),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=15, null=True)),
                ('month', models.PositiveIntegerField(default=9, validators=[app.validators.validate_date])),
                ('year', models.PositiveIntegerField(default=2022, validators=[app.validators.validate_year])),
                ('educenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
