# Generated by Django 3.2.9 on 2022-09-16 03:14

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_expenses_sidefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=16, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=16, null=True),
        ),
    ]
