# Generated by Django 3.2.9 on 2022-09-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sidefund_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidefund',
            name='doner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.useradmin'),
        ),
        migrations.AddField(
            model_name='sidefund',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
