# Generated by Django 3.2.9 on 2022-09-20 06:01

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220918_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthrevenue',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[app.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=20, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthrevenue',
            unique_together={('educenter', 'month')},
        ),
    ]
