# Generated by Django 3.2.9 on 2022-09-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220920_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthrevenue',
            unique_together=set(),
        ),
    ]
