# Generated by Django 3.2.9 on 2022-09-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_monthrevenue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthrevenue',
            name='educenter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.educenter'),
        ),
    ]
