# Generated by Django 3.2.9 on 2022-09-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_monthrevenue_educenter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthrevenue',
            unique_together={('educenter', 'month', 'year')},
        ),
    ]
