# Generated by Django 3.2.9 on 2022-09-22 17:23

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220922_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='adm_month',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='teacher',
            name='adm_year',
            field=models.IntegerField(default=2022, validators=[app.validators.validate_year]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='admission_date',
            field=models.IntegerField(default=22, validators=[app.validators.validate_date]),
        ),
    ]
