# Generated by Django 3.2.9 on 2022-09-23 03:07

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220922_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=23, null=True),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=23, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=23, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='adm_month',
            field=models.IntegerField(default=9, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='admission_date',
            field=models.IntegerField(default=23, validators=[app.validators.validate_date]),
        ),
    ]
