# Generated by Django 3.2.9 on 2022-09-24 04:26

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220923_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adm_month',
            field=models.PositiveIntegerField(default=9, validators=[app.validators.validate_date]),
        ),
        migrations.AddField(
            model_name='student',
            name='adm_year',
            field=models.PositiveIntegerField(default=2022, validators=[app.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=24, null=True),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=24, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=24, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='admission_date',
            field=models.IntegerField(default=24, validators=[app.validators.validate_date]),
        ),
    ]
