# Generated by Django 4.1.1 on 2022-11-12 06:34

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220924_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doners',
            name='month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='monthrevenue',
            name='month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='adm_month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='muqtadi',
            name='admission_date',
            field=models.IntegerField(default=12, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='salreciver',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='sidefund',
            name='month',
            field=models.PositiveIntegerField(blank=True, default=11, null=True, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='studoners',
            name='month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='teachdoner',
            name='month',
            field=models.PositiveIntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='adm_month',
            field=models.IntegerField(default=11, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='admission_date',
            field=models.IntegerField(default=12, validators=[app.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cnic',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[app.validators.validate_cnic]),
        ),
    ]
