# Generated by Django 4.1.1 on 2022-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_doners_month_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidefund',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
